### ISSUE TITLE
Add support for unresolved yaml tags

### ISSUE THREAD

**Issue by joshooaj** [joshooaj/mkdocs-deploy#1]
I'm using the `js-yaml` module right now and haven't fully wrapped my head around it and the idea of custom tags. Currently, the following YAML would cause the action to fail:

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
```

I think I want _any_ tag to be treated as a string as I'm only reading a user-supplied `mkdocs.yml` in order to retrieve the name of the theme, which is used to figure out which package to install to add support for the theme.

On the other hand, I might just _require_ a `requirements.txt` file if a `mkdocs.yml` is supplied, and expect that the requirements file already includes the theme. That way I only ever interact with yaml when writing a basic `mkdocs.yml` at runtime when no user-defined configuration was provided.
